# -*- coding: utf-8 -*-
######################################################################
# This file was *autogenerated* from the file /Users/Tiasa/Documents/graph_incidence_nonlocal_games/incidence_group_gen/example_complete_graph.sage.
######################################################################
_sage_const_5 = Integer(5)
from incidence_group_gen import incidence_group


# As an example, calculate the incidence graph for the K_5 complete graph.
graph = graphs.CompleteGraph(_sage_const_5 )
print(incidence_group(graph))
